### ISSUE TITLE
Scan not working

### ISSUE THREAD

**Issue by ThePrincelle** [AnthonyDeniau/PrivacyPolicy#1]
Whatever drug I’m trying to scan. Nothing happens.

**Comment by AnthonyDeniau** [comment]
Thanks for report, I will fix it soon

**Comment by AnthonyDeniau** [comment]
Bug fixed

**Comment by ThePrincelle** [comment]
Is it possible to update the app on the AppStore with this fix ?

**Comment by AnthonyDeniau** [comment]
The update should be pushed through Over The Air update. Could you try to close and release your app ?

**Comment by ThePrincelle** [comment]
Sorry, nothing has changed.
